### ISSUE TITLE
Sensi Thermostat no longer works in Homeassistant

### ISSUE THREAD

**Issue by calvinwhitt** [iprak/sensi#28] opened 2024-01-18 18:45 UTC
A recent update requires me to reconfigure my sensi integration.  What are you supposed to enter in the configuration? Only one entry needed but it takes nothing entered.

Thanks Cal

**Comment by dziban303** [comment] 2024-01-18 18:59
Same for me but there was no update. I just restarted Home Assistant and it happened.

![image](https://github.com/iprak/sensi/assets/7931765/0bcc101c-132e-4655-b74e-146525cba05d)

I'm not sure what it wants here but my sensi account password isn't it. I've tried creating a new instance, with my account username and password, but that's rejected immediately as well.

Since the mobile app still works fine, perhaps they've (sensi et al) enacted countermeasures against this and other hacky methods of accessing the API? @iprak

**Comment by iprak** [comment] 2024-01-18 19:07
See #27

**Comment by calvinwhitt** [comment] 2024-01-18 21:39
I uninstalled the Sensi integration and tried to reinstall the integration and it won't install. It will get as fall as putting in you Sensi login info but refuses the entries. My log doesn't show the activity relating to the problem.

**Comment by dziban303** [comment] 2024-01-18 21:44
@calvinwhitt again see #27

**Comment by Pheelix** [comment] 2024-01-19 04:15
Not sure if this can help or not.  But Homekit Device Integration connects and controls my Sensi Touch.  Maybe you can use Homekit as a slave integration or see how they are getting access.  I will post a few screenshot below.

![image](https://github.com/iprak/sensi/assets/3882473/42255d5c-1fbc-46b3-adb7-b5ef26636bc5)
![image](https://github.com/iprak/sensi/assets/3882473/7717dea5-7f82-436b-8028-d62052f6f8f4)
![image](https://github.com/iprak/sensi/assets/3882473/8eb7bdc0-ec89-4545-9727-03c1ad5f38e1)
![image](https://github.com/iprak/sensi/assets/3882473/bb00dd34-732b-475c-a4c6-1f424dc685c8)

Debug File from the Homekit Device Page.
[homekit_controller-Sensi-1418DD-debug.txt](https://github.com/iprak/sensi/files/13984157/homekit_controller-Sensi-1418DD-debug.txt)

**Comment by calvinwhitt** [comment] 2024-01-19 16:09
Thanks for the info. 
I tried your suggestions and had no luck.
I still have the same problem. incorrect login credentials. . My issue started with the last core update ( I think it was the last ). I wonder if the update broke things?
Thanks anyway.
    On Thursday, January 18, 2024 at 11:15:56 PM EST, Pheelix ***@***.***> wrote:  
 
 


Not sure if this can help or not. But Homekit Device Integration connects and controls my Sensi Touch. Maybe you can use Homekit as a slave integration or see how they are getting access. I will post a few screenshot below.

image.png (view on web)
image.png (view on web)
image.png (view on web)
image.png (view on web)

Debug File from the Homekit Device Page.
homekit_controller-Sensi-1418DD-debug.txt

**Comment by vshijiav** [comment] 2024-01-19 17:04
> Thanks for the info.  I tried your suggestions and had no luck. I still have the same problem. incorrect login credentials. . My issue started with the last core update ( I think it was the last ). I wonder if the update broke things? Thanks anyway. On Thursday, January 18, 2024 at 11:15:56 PM EST, Pheelix ***@***.***> wrote: Not sure if this can help or not. But Homekit Device Integration connects and controls my Sensi Touch. Maybe you can use Homekit as a slave integration or see how they are getting access. I will post a few screenshot below. image.png (view on web) image.png (view on web) image.png (view on web) image.png (view on web) Debug File from the Homekit Device Page. homekit_controller-Sensi-1418DD-debug.txt — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

As other already mentioned sensi changed their login auth so old ways of getting things done no longer works,
The only way of getting this work for now is using homekit (if you are using the homekit compatible device)
or using the smartthing(I haven`t tried but theoretically it works)

**Comment by Jpatrick2zo** [comment] 2024-01-19 17:44
I did some testing on the Sensi API and learned that the grant_type: password is seemingly more locked down now and doesn't work the same. 

I looked into how the Sensi iOS app does it's authentication and it's a bit different, using a grant_type of refresh_token. I changed a few things around in auth.py and managed to get it connected to HASS again so there still might be hope although right now the only way I was able to get the required refresh_token to use in the auth post request is with mitmproxy setup to capture the Sensi app traffic from an iPhone.

**Comment by vshijiav** [comment] 2024-01-19 17:48
> I did some testing on the Sensi API and learned that the grant_type: password is seemingly more locked down now and doesn't work the same.
> 
> I looked into how the Sensi iOS app does it's authentication and it's a bit different, using a grant_type of refresh_token. I changed a few things around in auth.py and managed to get it connected to HASS again so there still might be hope although right now the only way I was able to get the required refresh_token to use in the auth post request is with mitmproxy setup to capture the Sensi app traffic from an iPhone.

I was thinking about the same using traffic monitoring proxy to capture token actually but I don`t have the time to check, good to hear it works now. Also I can confirm smartthing and homekit both works for now, we can still enjoy sensi thermostat on homeassistant for now.

**Comment by calvinwhitt** [comment] 2024-01-19 19:49
Thanks for the reply. I tried getting through to the Sensi folks and got put on terminal hold. My last login attempt showed they were having server issues.
Sounds as if their login database died.
    On Friday, January 19, 2024 at 12:44:17 PM EST, 2z0 ***@***.***> wrote:  
 
 


I did some testing on the Sensi API and learned that the grant_type: password is seemingly more locked down now and doesn't work the same.

I looked into how the Sensi iOS app does it's authentication and it's a bit different, using a grant_type of refresh_token. I changed a few things around in auth.py and managed to get it connected to HASS again so there still might be hope although right now the only way I was able to get the required refresh_token to use in the auth post request is with mitmproxy setup to capture the Sensi app traffic from an iPhone.

**Comment by iprak** [comment] 2024-01-19 21:20
I would go with Smarthings as an alternative. This change in behavior feels very much like MyQ garage opener which stopped working and was subsequently removed from HomeAssistant.

**Comment by macwriter** [comment] 2024-01-20 00:59
Using the `{"grant_type":"password"}`, I added the following headers to the post command (auth.py) and it is working.

`headers = {"Content-Type": "application/x-www-form-urlencoded; charset=utf-8",
           "accept": "*/*",
           "x-platform":"android"}`

`response = await session.post(OAUTH_URL.format(device_id), data=post_data, headers=headers)`

**Comment by iprak** [comment] 2024-01-20 01:03
Awesome. I will give it a try.

**Comment by iprak** [comment] 2024-01-20 02:35
This should be fixed now

**Comment by robertofelix** [comment] 2024-01-20 03:20
I can confirm it's working. Good job, guys!

**Comment by iprak** [comment] 2024-01-20 13:43
It was all @macwriter

**Closed by iprak** 2024-01-20 13:43 UTC

**Comment by calvinwhitt** [comment] 2024-01-22 17:55
I found another cause for this problem. After finally getting someone at Sensi I had to uninstall and reinstall their mobile app, set a new password and things started working again in the mobile app and after reinstalling things in Homeassistant, all started working again. Thanks to all for your previous suggestions.
